version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./:/code
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mypassword