version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DB_CONN_URL: postgres://postgres:mypassword@postgres:5432/postgres
      PORT: 8080
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./:/code
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mypassword